### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by emodeqidao** [boyXiong/ClickCountOfButton#1]
在你的Demo 上面添加了一个 打开相册的 view 
Test:  https://github.com/emodeqidao/ClickCountOfButton-master-2/tree/master/ClickCountOfButton
设备：iOS9.1.3  
操作步骤： 打开相册之后  跟着点击取消  就crash ， 这个bug 在iOS7，8 下 是没问题  。 在9 就有问题

**Comment by boyXiong** [comment]
已经修复
